#!/usr/bin/python

import argparse
import os.path

parser = argparse.ArgumentParser(description='Convert binary to C.')
parser.add_argument(
	'-i', '--input',
	metavar='input_filename',
	type=str,
	nargs=1,
	required=True,
	help='Filename of the binary file.',
)
parser.add_argument(
	'-n', '--name',
	metavar='name',
	type=str,
	nargs=1,
	required=False,
	help='Name for the object to create.',
)

args = parser.parse_args()
in_filename = args.input[0]
if args.name:
	name = args.name[0]
else:
	name = os.path.basename(in_filename).replace('.', '_').lower()

with open(in_filename) as f:
	contents = f.read()

template = '''
unsigned char {name}[] = {{ {contents} }};

unsigned int {name}_len = {len};
'''

print(template.format(
	name=name,
	contents=', '.join(str(ord(c)) for c in contents),
	len=len(contents)),
)
